name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install for main directory
      - run: npm install

      - name: npm test and build for main directory
        run: |
          npm run test
          npm run build

      - name: npm install for example directory
        working-directory: ./example
        run: npm install
